### ISSUE TITLE
“Guid should contain 32 digits” serilog error even when a valid guid is used

### ISSUE THREAD

**Issue by DylanTusler** [serilog/serilog-enrichers-thread#17]
We are experiencing a number of cases when we see an error with this kind of stack trace:
2020-04-20T08:38:17.5145399Z Exception while emitting periodic batch from Serilog.Sinks.MSSqlServer.MSSqlServerSink: System.ArgumentException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).Couldn't store <"7526f485-ec2d-4ec8-bd73-12a7d1c49a5d"> in UserId Column.  Expected type is Guid.
 ---> System.FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
   at System.Guid.GuidResult.SetFailure(Boolean overflow, String failureMessageID)
   at System.Guid.TryParseExactD(ReadOnlySpan`1 guidString, GuidResult& result)
   at System.Guid.TryParseGuid(ReadOnlySpan`1 guidString, GuidResult& result)
   at System.Guid..ctor(String g)
   at System.Data.Common.ObjectStorage.Set(Int32 recordNo, Object value)
   at System.Data.DataColumn.set_Item(Int32 record, Object value)
   --- End of inner exception stack trace ---
   at System.Data.DataColumn.set_Item(Int32 record, Object value)
   at System.Data.DataRow.set_Item(DataColumn column, Object value)
   at Serilog.Sinks.MSSqlServer.MSSqlServerSink.FillDataTable(IEnumerable`1 events)
   at Serilog.Sinks.MSSqlServer.MSSqlServerSink.EmitBatchAsync(IEnumerable`1 events)
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.OnTick()

This arises when using LogContext.PushProperty("UserId", someGuid);
someGuid is a Guid type variable, and contains a valid Guid.

It is not easily reproducible, unfortunately, but the end result is that our log entries are not being written when this kicks in.

I [posted on StackOverflow](https://stackoverflow.com/questions/61318331/guid-should-contain-32-digits-serilog-error-with-sql-server-sink) some months ago with this issue, but have been unable to resolve it satisfactorily.

Wondering if there was any insight that could be offered? I'm not sure if it is an issue with serilog-enrichers-thread or with the sql server sink. I'm starting here, as the issue only arises in connection with items added with PushProperty.

Edited to Add:
This stackoverflow link from 4 years ago seems related: https://stackoverflow.com/questions/35178415/unable-to-log-in-ms-sql-using-serilog

**Comment by skomis-mm** [comment]
Hi @DylanTusler ,

According to the stack trace it seems `UserId` is of string type (`at System.Guid..ctor(String g)`). The parse error occurs because of quotes around the string representation of the value.

If it is occurs occasionally can you check if the `UserId` not overriden after the `LogContext.PushProperty` call?
```csharp
LogContext.PushProperty("UserId", Guid.NewGuid()); // UserId is of Guid type
...
Log.Information("Hello, {UserId}", Guid.NewGuid().ToString()); // override UserId with new value and type (string) 
```

**Comment by DylanTusler** [comment]
Hi, yes, on further investigation, this is exactly what has happened. I am wondering if there is any way to mitigate this going forward? I can fix my codebase but I can't prevent someone else from making this mistake in the future. And the fact that this is effectively a silent failure is troubling.

**Comment by nblumhardt** [comment]
It seems to me that the MSSQL sink should be extracting the string `Value` property from the `ScalarValue`, rather than calling `ToString()` on it (if that's what's going on) - perhaps this bug could move over to the MSSQL sink repo?

**Comment by DylanTusler** [comment]
I've raised an issue in the other repo: https://github.com/serilog/serilog-sinks-mssqlserver/issues/312

**Comment by nblumhardt** [comment]
Great, thanks Dylan!
